SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeId] [int] NOT NULL,
	[CompanyId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
	[IsActiveEmployee] [int] NOT NULL,
	[IsTrAvailable] [int] NOT NULL,
	[IsPmAvailable] [int] NOT NULL,
	[IsCallCenter] [int] NOT NULL,
	[IsVendor] [int] NOT NULL,
	[IsAccountLocked] [int] NOT NULL,
	[IsMasterAuthor] [int] NOT NULL,
	[IsPropertyAuthor] [int] NOT NULL,
	[IsSubscriptionEnabled] [int] NOT NULL,
	[ShowTR] [int] NOT NULL,
	[ShowPM] [int] NOT NULL,
	[ShowSM] [int] NOT NULL,
	[UsesReports] [int] NOT NULL,
	[UsesSetup] [int] NOT NULL,
	[ReceivesNewsletters] [int] NOT NULL,
	[ReceivesAnnouncements] [int] NOT NULL,
	[ReceivesServiceAlerts] [int] NOT NULL,
	[EmployeeHomePage] [int] NOT NULL,
	[NotifyMissingValues] [int] NOT NULL,
	[NotifyCallAttention] [int] NOT NULL,
	[FailedLoginAttempts] [int] NOT NULL,
	[EmployeeFirstName] [varchar](50) NOT NULL,
	[EmployeeLastName] [varchar](50) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[ExternalEmployeeCode] [varchar](50) NOT NULL,
	[PhoneNumber] [varchar](50) NOT NULL,
	[TRDeviceType] [int] NOT NULL,
	[TRDeviceAddress] [varchar](128) NOT NULL,
	[TRCCEmailAddress] [varchar](512) NOT NULL,
	[PMDeviceType] [int] NOT NULL,
	[PMDeviceAddress] [varchar](128) NOT NULL,
	[TRDeviceTypeDescription] [varchar](50) NOT NULL,
	[PMDeviceTypeDescription] [varchar](50) NOT NULL,
	[NotifyEmailAddress] [nvarchar](128) NOT NULL,
	[SubscriptionEmailAddress] [varchar](128) NOT NULL,
	[LocaleCode] [char](5) NOT NULL,
	[PasswordChangeDate] [smalldatetime] NOT NULL,
	[LastLoginDate] [smalldatetime] NOT NULL,
	[PasswordExpiryDate] [smalldatetime] NOT NULL,
	[EncryptedPassword] [binary](20) NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[DateUpdated] [datetime] NOT NULL,
	[tmpEmployeeId] [int] NOT NULL,
	[IsEecoAvailable] [int] NOT NULL,
	[ShowEECO] [int] NOT NULL,
	[EECODeviceType] [int] NOT NULL,
	[EECODeviceAddress] [varchar](128) NOT NULL,
	[EmergencyPhone1] [varchar](50) NOT NULL,
	[EmergencyPhone2] [varchar](50) NOT NULL,
	[EmergencySMS] [varchar](50) NOT NULL,
	[EmergencyEmail] [nvarchar](128) NOT NULL,
	[EmergencyEmployeeIdEnteredBy] [int] NOT NULL,
	[EmergencyDateFrom] [smalldatetime] NOT NULL,
	[IsPool] [int] NOT NULL,
	[EmployeeIdAlternate] [int] NULL,
	[MobileVersion] [varchar](15) NOT NULL,
	[ForwardStartDate] [smalldatetime] NOT NULL,
	[ForwardEndDate] [smalldatetime] NOT NULL,
	[UsesMobile] [int] NOT NULL,
	[AppleDeviceToken] [varchar](64) NOT NULL,
	[ShowWelcomePage] [int] NOT NULL,
	[ShowVendorCoi] [int] NOT NULL,
	[ShowTenantCoi] [int] NOT NULL,
	[IsTenantCoiContact] [int] NOT NULL,
	[IsVendorCoiContact] [int] NOT NULL,
	[EmployeeSignature] [varchar](512) NOT NULL,
	[DateUpdatedUtc] [datetime] NOT NULL,
	[DateCreatedUtc] [datetime] NOT NULL,
	[CanViewPortfolioData] [int] NOT NULL,
	[IsPiAvailable] [int] NOT NULL,
	[ShowPI] [int] NOT NULL,
	[CanCreatePIProperty] [int] NOT NULL,
	[PrimaryEmailAddress] [nvarchar](128) NOT NULL,
	[EmployeeTitle] [nvarchar](50) NOT NULL,
	[DeviceNotes] [nvarchar](512) NOT NULL,
	[Employee_CS_CompanyId] [int] NOT NULL,
	[FcmDeviceId] [nvarchar](256) NOT NULL,
	[TenantIdScope] [int] NULL,
	[LearningId] [int] NOT NULL,
	[LearningUserType] [int] NOT NULL,
	[GeoDispatchEnabled] [int] NOT NULL,
	[EmployeeStatus] [varchar](20) NOT NULL,
	[TravellingMethod] [varchar](20) NULL,
	[DateEmployeeStatusUpdated] [datetimeoffset](7) NOT NULL,
	[GPSMode] [nvarchar](20) NOT NULL,
	[CredentialTokenDateExpiryUtc] [datetime] NULL,
	[CredentialToken] [varchar](50) NOT NULL,
	[CanSSOLogin] [int] NOT NULL,
	[CanScanAssetCode] [int] NOT NULL,
	[LearningRoleId] [int] NOT NULL,
	[UsesGen5] [int] NOT NULL,
	[EmployeeCode] [uniqueidentifier] NOT NULL,
	[RequireLmsRoleUpdate] [int] NOT NULL,
	[RequireLmsScopeUpdate] [int] NOT NULL,
	[UsesCms] [int] NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY NONCLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85)
) ON [PRIMARY]
GO
